### ISSUE TITLE
cannot authenticate with Facebook oAuth

### ISSUE THREAD

**Issue by heyitsjames** [antonshevchenko/pager#2]
Error occurs when trying to click the `login with Facebook` button. This is running on the `https://pagerapp2.localtunnel.me/#/`, not just `http://localhost:3000`

![screen shot 2015-05-03 at 10 18 18 pm](https://cloud.githubusercontent.com/assets/828700/7449103/8ca7ac46-f1e2-11e4-8a65-60527fb07674.png)

**Comment by KKDeep** [comment]
Even I'm getting the same at localhost:3000

**Comment by Luehrsen** [comment]
The connected facebook app is simply not public yet. For the time beeing try going into app.js line 5 and change the app id to an app you manage.

**Comment by alisterdev** [comment]
The message that Facebook gives you says it all. Also, Luehrsen is absolutely right.

**Comment by KKDeep** [comment]
After changing the appid this is the message I'm getting.
"Given URL is not permitted by the Application configuration: One or more of the given URLs is not permitted by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

**Comment by benhanks040888** [comment]
@KKDeep The site url of your Facebook App must be either http://localhost:3000/ if you're using localhost or the localtunnel url if you're using localtunnel

**Comment by benhanks040888** [comment]
You have to use the https://pagerapp2.localtunnel.me apparently, since all the API url points to there.
